### PR TITLE
fix: remove whitespace

### PR DESCRIPTION
**Pull request by shawaj**
remove whitespace in toml files

### CODE REVIEW

**Comment by disk91** [comment]
I love white spaces

**Comment by shawaj** [comment]
It's not removing blank lines, it is removing blank spaces at the end of lines and on empty lines.

They tend to break stuff

**Comment by disk91** [comment]
trailing whitespace are in comments and empty line in your proposal, if that break stuff, what no-one experienced yet, better to create an issue on Chirpsatck project to fix that as having spaces in configuration file is a normal situation.

**Comment by shawaj** [comment]
> if that break stuff, what no-one experienced yet

Why do you think I opened the PR? Precisely because it **did** break stuff 🤦

Having trailing whitespace in configuration files isn't a normal situation and it does break stuff, regularly. Hence why every code linter in the world will throw an error on trailing whitespace.

**Pull request closed without merging**
